//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonTokenV1.DataMML
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEUDASCONDUCTORES
    {
        public string CONCEPTO { get; set; }
        public string DES_MERCADO { get; set; }
        public string COD_PUESTO { get; set; }
        public string COD_PASAJE { get; set; }
        public string COD_LETRA { get; set; }
        public string CANO { get; set; }
        public string PERIODO { get; set; }
        public Nullable<decimal> VALOR1 { get; set; }
        public Nullable<decimal> EMISION { get; set; }
        public Nullable<decimal> SERVICIO { get; set; }
        public Nullable<decimal> MORA { get; set; }
        public string COD_MERCADO { get; set; }
        public string DOC_IDENTIDAD { get; set; }
        public string COD_NOMBRE { get; set; }
        public string NUM_CONTRATO { get; set; }
        public string ANO_CONTRATO { get; set; }
        public Nullable<System.DateTime> INI_CONTRATO { get; set; }
        public Nullable<System.DateTime> FIN_CONTRATO { get; set; }
        public Nullable<decimal> MON_CONTRATO { get; set; }
        public string AUTPAGO { get; set; }
        public string ESTADO_DEL_PUESTO { get; set; }
    }
}
