//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonTokenV1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public decimal IDUSUARIO { get; set; }
        public decimal DNI { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public System.DateTime DATE_CREADO { get; set; }
    }
}
